language: node_js
node_js:
   - "17.3"
dist: trusty
services:
  - postgresql
  - docker
env:
  - NODE_VER="17.3.0" NODE_ENV=ci DB_NAME=turmoil DB_USERNAME=postgres DB_PASSWORD=nopass DB_HOST=127.0.0.1 APP_SECRET=turmoil-secret-key
cache:
  directories:
    - turmoil-backend/node_modules
    - turmoil-frontend/node_modules
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 14 -L GPL
  - pwd
  - ls -la
  - chmod +x ./gradlew
install:
  - npm run install:backend
  - npm run build:frontend
  - ./gradlew build
  - ls -la build
  - ls -la build/libs
before_script:
  - docker build --build-arg JAR_FILE=build/*.jar -t nemhauser/turmoil-java .
  - docker run -d -p 127.0.0.1:8080:8080 nemhauser/turmoil-java /bin/sh -c "java --jar /app.jar;"
  - psql -c 'create database turmoil;' -U postgres
script:
  - nohup npm run start:backend &
  - nohup npm run start:frontend &
  - sleep 10
  - npm test
