mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: nopass
    MYSQL_DATABASE: turmoil
  volumes:
    - ./data:/docker-entrypoint-initdb.d