export const UPDATE_CHARACTER_STATE = 'UPDATE_CHARACTER_STATE';
export const UPDATE_ITEMS_IN_EQUIPMENT = 'UPDATE_ITEMS_IN_EQUIPMENT';
export const UPDATE_ITEMS_IN_STASH = 'UPDATE_ITEMS_IN_STASH';
export const UPDATE_ENEMY_UNITS = 'UPDATE_ENEMY_UNITS';
export const UPDATE_FRIENDLY_UNITS = 'UPDATE_FRIENDLY_UNITS';
